#!/opt/homebrew/bin/zsh

CYAN='\033[0;36m'
NC='\033[0m' # No Color

clog() {
  echo "${CYAN}>>>>> $1 <<<<<${NC}"
}

chsh -s $(which zsh)
if grep -q "export PATH" ~/.zshrc
then
    clog "found \"export PATH\" in ~/.zshrc, skipping update"
    clog "existing PATH:"
    echo $PATH
else
    clog "updating PATH..."
    echo "export PATH=\"/usr/local/bin:/usr/local/sbin:~/bin:/opt/homebrew/bin:\$PATH\"" >> ~/.zshrc
    source ~/.zshrc
    clog "updated PATH:"
    echo $PATH
fi

echo ""

clog "creating ~/Applications for personal applications..."
mkdir -p ~/Applications

if grep -q "HOMEBREW_CASK_OPTS" ~/.zshrc
then
    clog "found HOMEBREW_CASK_OPTS in ~/.zshrc, skipping update"
else
    clog "updating homebrew cask install directory to ~/Applications..."
    echo "export HOMEBREW_CASK_OPTS=\"--appdir=~/Applications\"" >> ~/.zshrc
    source ~/.zshrc
fi

echo ""

clog "updating global npm config..."
./npm/global-config
echo Done!
clog "installing global npm packages..."
./npm/global-packages
echo Done!

echo ""

clog "installing latest node..."
source ~/.nvm/nvm.sh
nvm install --lts
echo Done!

clog "installing brew packages and casks..."
brew doctor
brew update
brew bundle --file brew/Brewfile

clog "running install script..."
./install
